
website:
    resource: "@WebsiteBundle/Resources/config/routing.yml"
    
crm_fos_user:
    resource: "@CrmFosUserBundle/Resources/config/routing.yml"

crm_auditing:
    resource: "@CrmAuditingBundle/Resources/config/routing.yml"
    prefix:   /

crm_notification:
    resource: "@CrmNotificationBundle/Resources/config/routing.yml"
    prefix:   /

crm_mailing:
    resource: "@CrmMailingBundle/Resources/config/routing.yml"
    prefix:   /

crm_brooker_inventory:
    resource: "@CrmBrookerInventoryBundle/Resources/config/routing.yml"
    prefix:   /

crm_sandbox:
    resource: "@CrmSandboxBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /usermanagement/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

comur_image:
    resource: "@ComurImageBundle/Resources/config/routing.yml"
    prefix:   /
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
#HWIOAuthBundle routes
#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

google_login:
    pattern: /login/check-google

simple_things_entity_audit:
    resource: "@SimpleThingsEntityAuditBundle/Resources/config/routing.yml"
    prefix: /audit