<?php

namespace Crm\SandboxBundle\DAO;

use Doctrine\ORM\EntityRepository;

/**
 * ComplaintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplaintRepository extends EntityRepository
{
}
