<?php

namespace Crm\SandboxBundle\DAO;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
	public function checkIfMobileExists($mobile,$mobile2)
	{	
		$query = $this->getEntityManager()->createQuery(
			"
			SELECT c
			from CrmSandboxBundle:Contact c
			where (c.mobile = :mobile)
			or (c.mobile = :mobile2)
			or (c.mobile2 = :mobile)
			or (c.mobile2 = :mobile2)
			"
			)
			->setParameter('mobile', $mobile)
			->setParameter('mobile2', $mobile2)
			;
			
			return ($query->getResult());
	}
}
