<?php

namespace Crm\SandboxBundle\DAO;

/**
 * SubChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubChannelRepository extends \Doctrine\ORM\EntityRepository
{
}
