<?php

namespace Crm\BrookerInventoryBundle\DAO;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyTypeRepository extends \Doctrine\ORM\EntityRepository
{


}
